addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:zoogie/sdl2-snapshots'
        packages:
            - clang-3.7
            - g++-5
            - gcc-5
            - libsdl2-dev
            - libsdl2-image-dev

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo ../travis/linux_cmake.sh ; fi

language: cpp

compiler:
  - gcc

script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./travis/script_linux.sh ; fi

