# See https://jonasw.de/blog/2015/07/22/develop/cplusplus14-on-travis-with-cmake/
addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:zoogie/sdl2-snapshots'
        packages:
            - clang-3.7
            - g++-5
            - gcc-5
            - libsdl2-dev
            - libsdl2-image-dev

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo ./travis/linux_cmake.sh ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export PATH=$HOME/cmake-3.3.1-Linux-x86_64/bin:$PATH ; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi

language: cpp

compiler:
  - gcc

script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./travis/script_linux.sh ; fi

