# See https://jonasw.de/blog/2015/07/22/develop/cplusplus14-on-travis-with-cmake/
os:
  - linux
  - osx

language: cpp

compiler:
  - gcc
  - clang

addons:
    apt:
        sources:
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:zoogie/sdl2-snapshots'
        packages:
            - clang-3.8
            - clang-format-3.8
            - clang-tidy-3.8
            - cppcheck
            - g++-5
            - gcc-5
            - libsdl2-dev
            - libsdl2-image-dev

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install sdl2; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install sdl2_image; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install llvm --with-clang; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export PATH="${PATH}:/usr/local/opt/llvm/bin/"; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install clang-format; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install cppcheck; fi

  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo ./ci/travis/linux_cmake.sh ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export PATH=$HOME/cmake-3.3.1-Linux-x86_64/bin:$PATH ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$CXX" = "clang++" ]; then export CXX="clang++-3.8" CC="clang-3.8"; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CLANG_FORMAT=clang-format-3.8; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CLANG_TIDY=clang-tidy-3.8; fi
# install OCLint on Linux, already part of OSX images
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then eval "$(curl -sL https://raw.githubusercontent.com/ryuichis/oclint-cpp-travis-ci-examples/master/oclint-ci-install.sh)"; fi


script:
  - ./ci/travis/script_unix.sh
